### PR TITLE
Updated Project Name in bootstrap.yml

### PR DESCRIPTION
**Pull request by jusoto**
Renaming the project name from 'user-service' to 'userservice'

### CODE REVIEW

**Comment by Castyr** [comment]
Looks good

**Review by Castyr — APPROVED** [review]

**Comment by jusoto** [comment]
[Refactor User-service for licensing](https://trello.com/c/RzFrHOuC/88-refactor-user-service-for-licensing)

**Comment by jusoto** [comment]
[Change name of project user-sevice to userservice](https://trello.com/c/vchgdvBC/120-change-name-of-project-user-sevice-to-userservice)

**Comment by jusoto** [comment]
[Implement documentation for authentication service](https://trello.com/c/UPKLe10b/118-implement-documentation-for-authentication-service)

**Comment by jusoto** [comment]
[Implement documentation for authentication service](https://trello.com/c/UPKLe10b/118-implement-documentation-for-authentication-service)

**Pull request merged**
